
runtime: go118

main: cmd/botapi
handlers:

  # All URLs are handled by the Go application script
  - url: /.*
    script: auto
<<<<<<< HEAD
<<<<<<< HEAD

=======
>>>>>>> develop
=======
<<<<<<< HEAD
<<<<<<< HEAD

=======
>>>>>>> develop
=======
<<<<<<< HEAD
<<<<<<< HEAD

=======
>>>>>>> develop
=======
>>>>>>> main
=======

=======
>>>>>>> develop
>>>>>>> 85d2138019cdfe478efd1de2cea90b8e46aad954
<<<<<<< HEAD
>>>>>>> develop
=======
<<<<<<< HEAD
>>>>>>> develop
=======
>>>>>>> main
>>>>>>> develop
