version: '3.9'
services:
  app:
    build:
     context: .
     dockerfile: Dockerfile
    ports:
     - "8080:8080"
    tty: true
  db:
    image: postgres
    environment:
      POSTGRES_USER: yamadatarou
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: line_bot
    ports:
      - "8000:8000"